'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1011316_grunge_frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1011316-grunge-frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _10253847_urea_fertilizer_or_46_0_0_formula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10253847-urea-fertilizer-or-46-0-0-formula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _11845640_word_on_the_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11845640-word-on-the-button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _11866657_laptop_with_steel_security_lock_password_3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11866657-laptop-with-steel-security-lock-password-3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _12649536_login_interface_written_with_chalk_on_blackboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12649536-login-interface-written-with-chalk-on-blackboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _12649536_login_interface_written_with_chalk_on_blackboard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12649536-login-interface-written-with-chalk-on-blackboard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _12689233_word_on_keyboard_made_in_3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12689233-word-on-keyboard-made-in-3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13018127_word_on_laptop_made_in_3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13018127-word-on-laptop-made-in-3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13320771_computer_login_browser_drawn_with_chalk_on_blackboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13320771-computer-login-browser-drawn-with-chalk-on-blackboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13381560_word_on_laptop_made_in_3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13381560-word-on-laptop-made-in-3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13753674_fertilizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13753674-fertilizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _14697987_empty_wooden_sign_with_green_wheat_grass__isolated_on_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14697987-empty-wooden-sign-with-green-wheat-grass--isolated-on-white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _14697987_empty_wooden_sign_with_green_wheat_grass__isolated_on_white1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14697987-empty-wooden-sign-with-green-wheat-grass--isolated-on-white1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _14697987_empty_wooden_sign_with_green_wheat_grass__isolated_on_white2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14697987-empty-wooden-sign-with-green-wheat-grass--isolated-on-white2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15281753_fresh_green_grass_frame_on_white_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15281753-fresh-green-grass-frame-on-white-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15281753_fresh_green_grass_frame_on_white_background__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15281753-fresh-green-grass-frame-on-white-background (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15281753_fresh_green_grass_frame_on_white_background__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15281753-fresh-green-grass-frame-on-white-background (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15281753_fresh_green_grass_frame_on_white_background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15281753-fresh-green-grass-frame-on-white-background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15358912_word_on_yellow_wall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15358912-word-on-yellow-wall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15358912_word_on_yellow_wall1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15358912-word-on-yellow-wall1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15602493_word_on_the_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15602493-word-on-the-button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15602493_word_on_the_button1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15602493-word-on-the-button1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15710383_word_on_black_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15710383-word-on-black-button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16501525_abstract_word_cloud_for_fertilizer_with_related_tags_and_terms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16501525-abstract-word-cloud-for-fertilizer-with-related-tags-and-terms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _263444_xcitefun_wonderful_3d_nature_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("263444,xcitefun-wonderful-3d-nature-6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _263447_xcitefun_wonderful_3d_nature_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("263447,xcitefun-wonderful-3d-nature-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2691755_fertilizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2691755-fertilizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2691755_fertilizer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2691755-fertilizer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3280049_mineral_fertilizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3280049-mineral-fertilizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3280049_mineral_fertilizer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3280049-mineral-fertilizer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3280049_mineral_fertilizer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3280049-mineral-fertilizer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3315707_mineral_fertilizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3315707-mineral-fertilizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3315707_mineral_fertilizer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3315707-mineral-fertilizer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3887192_fertilizer_to_pour_in_hands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3887192-fertilizer-to-pour-in-hands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3887194_fertilizer_to_pour_in_hands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3887194-fertilizer-to-pour-in-hands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3887194_fertilizer_to_pour_in_hands1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3887194-fertilizer-to-pour-in-hands1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3887195_fertilizer_to_pour_in_hands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3887195-fertilizer-to-pour-in-hands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3887195_fertilizer_to_pour_in_hands1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3887195-fertilizer-to-pour-in-hands1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3961174_grunge_background_with_autumn_leaves() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3961174-grunge-background-with-autumn-leaves", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5030619_a_lawn_with_dandelions_with_a_blank_sign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5030619-a-lawn-with-dandelions-with-a-blank-sign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5902754_fertilizer_icon_set_isolated_on_a_white_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5902754-fertilizer-icon-set-isolated-on-a-white-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5902754_fertilizer_icon_set_isolated_on_a_white_background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5902754-fertilizer-icon-set-isolated-on-a-white-background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _627550556logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("627550556logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6691277_round_progress_loading_indicator_vector_illustration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6691277-round-progress-loading-indicator-vector-illustration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6691277_round_progress_loading_indicator_vector_illustration1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6691277-round-progress-loading-indicator-vector-illustration1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _692448() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("692448", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7340506_fertilizer_bag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7340506-fertilizer-bag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7340506_fertilizer_bag1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7340506-fertilizer-bag1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _794995_garden_dirt_with_fertilizer_on_a_white_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("794995-garden-dirt-with-fertilizer-on-a-white-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8041892_urea_fertilizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8041892-urea-fertilizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9779805_man_pushing_a_shopping_cart_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9779805-man-pushing-a-shopping-cart-empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _998313_grunge_frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("998313-grunge-frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_dialog_cancel_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions-dialog-cancel-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_list_add_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions-list-add-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property at_gold_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("at-gold-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backro_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backro copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backround() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backround", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boxes_lighting_backdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boxes-lighting-backdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop_wallpaper_29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop-wallpaper-29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop_wallpaper_291() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop-wallpaper-291", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property field_arable_land_lines_ranks_agriculture_54020_1920x1200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("field_arable_land_lines_ranks_agriculture_54020_1920x1200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen_capture_1132013_21855_PM_bmp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen capture 1132013 21855 PM.bmp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen_capture_242013_35407_PM_bmp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen capture 242013 35407 PM.bmp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fullscreen_capture_242013_45858_PM_bmp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fullscreen capture 242013 45858 PM.bmp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grass_green_g_backgrounds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass-green-g-backgrounds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grass_green_g_backgrounds_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass-green-g-backgrounds copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hd_wallpaper2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hd-wallpaper2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kghostview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kghostview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property l2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magnifying_glass_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnifying-glass-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MB900282865() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MB900282865", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MB900283927() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MB900283927", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MB9002839271() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MB9002839271", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MH900174033() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MH900174033", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pencil_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property purple_gradient_backgrounds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("purple-gradient-backgrounds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_line_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_line_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red_line_background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_line_background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search-icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_footage_growing_golden_title_frame_and_flowers_on_green_background_hd_cg_animation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-footage-growing-golden-title-frame-and-flowers-on-green-background-hd-cg-an"& _ 
                        "imation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_footage_growing_golden_title_frame_on_blue_background_with_flowers_hd_cg_animation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-footage-growing-golden-title-frame-on-blue-background-with-flowers-hd-cg-an"& _ 
                        "imation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_footage_wire_frame_abstract_looping_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-footage-wire-frame-abstract-looping-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_footage_wire_frame_terrain_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-footage-wire-frame-terrain-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_footage_yellow_retro_flourishes_frame_loop_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-footage-yellow-retro-flourishes-frame-loop-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thm_arrowpin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thm_arrowpin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thm_buttrfly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thm_buttrfly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_1_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-1 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vector_Illustration_Of_Palm_Tree_Frame_Background_188ec70() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vector-Illustration-Of-Palm-Tree-Frame-Background-188ec70", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vector_Illustration_Of_Palm_Tree_Frame_Background_188ec70_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vector-Illustration-Of-Palm-Tree-Frame-Background-188ec70 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vector_Illustration_Of_Palm_Tree_Frame_Background_188ec701() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vector-Illustration-Of-Palm-Tree-Frame-Background-188ec701", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vintage_paper_scroll1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vintage-paper-scroll1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wheat_ears_on_burlap_background_sjpg38892() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheat_ears_on_burlap_background_sjpg38892", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wheat_ears_on_burlap_background_sjpg388921() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheat_ears_on_burlap_background_sjpg388921", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
