'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JET_AIRWAYS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _2006082400040101_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2006082400040101[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _xDR__Rock_On_____00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("[xDR] Rock On!! - 00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flight_status_Notification_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flight_status_Notification[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_custrelation_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_custrelation[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jet_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jet[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jet_Airways_Banner_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jet_Airways_Banner[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jet_Airways_Banner_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jet_Airways_Banner[1]1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jet_Airways_Banner_1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jet_Airways_Banner[1]2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jet_Airways_Banner_1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jet_Airways_Banner[1]3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jet_airways_cabin_crew_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jet-airways-cabin-crew[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jet_airways_cabin_crew_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jet-airways-cabin-crew[1]1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jet_Airways_commence_flights_srilanka_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jet-Airways-commence-flights-srilanka[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jet_airways_flight_schedule_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jet-airways-flight-schedule[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jet1_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jet1[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jet1_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jet1[1]1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jetairways_logo_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jetairways_logo[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jetairways_logo_1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jetairways_logo[1]1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jetairways_logo_1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jetairways_logo[1]2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JetAirways_plane_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JetAirways_plane[1]", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
